version: '3.9'

services:
    frontend:
        image: nginx:alpine
        container_name: frontend
        restart: unless-stopped
        volumes:
            - './frontend:/usr/share/nginx/html'
        ports:
            - '80:80'
        depends_on:
            - backend
    backend:
        build:
            context: ./backend
        container_name: backend
        restart: unless-stopped
        environment:
            CHOKIDAR_USEPOLLING: 'true'
        volumes:
            - './backend:/code'
            - './logs/backend:/code/logs'
            - './frontend/images:/code/images'
        command: 'sh run_server.sh'
        ports:
            - '127.0.0.1:${BE_PORT}:8001'
        links:
            - database
        depends_on:
            - database
    database:
        image: mysql:5.7
        container_name: database
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_SCHEMA}'
            MYSQL_USER: '${DB_USER}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './database/data:/var/lib/mysql'
            - './database/logs:/var/log/mysql'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb-flush-log-at-trx-commit=0
        ports:
            - '127.0.0.1:3306:3306'
